### ISSUE TITLE
Mod does not work with developer version of Minetest

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/qa_block#9]
As of Minetest commit cc7c31a5bc44ab0010997e86c0a8c9f5f832b398, `qa_block` does not work. When I start the world, I immediately get this error:

```
2016-12-21 13:11:01: ERROR[Main]: ModError: Failed to load and run script from /home/wuzzy/src/minetest/git/minetest/bin/../mods/qa_block/init.lua:
2016-12-21 13:11:01: ERROR[Main]: .../src/minetest/git/minetest/bin/../mods/qa_block/init.lua:63: bad argument #1 to 'ipairs' (table expected, got string)
2016-12-21 13:11:01: ERROR[Main]: stack traceback:
2016-12-21 13:11:01: ERROR[Main]: 	[C]: in function 'ipairs'
2016-12-21 13:11:01: ERROR[Main]: 	.../src/minetest/git/minetest/bin/../mods/qa_block/init.lua:63: in function 'print'
2016-12-21 13:11:01: ERROR[Main]: 	.../src/minetest/git/minetest/bin/../mods/qa_block/init.lua:138: in main chunk
```

**Comment by bell07** [comment]
I checked out the last version now and tried it. The qa_block does not have the issue on my system.
 I think the issue is not minetest related but maybe lua,
init.lua:138 calls `print("qa_block INFO: entering trusted or not restricted environment ;)")`
print is redefned by `print = function(...)`
args in line 63 should be a table, but it is a string in our case, I do not know why. Any changes on args syntax in Lua versions? Did you upgraded lua? I am still on 5.1.5

**Comment by Wuzzy2** [comment]
As far I know Minetest is using Lua 5.1 since ages. And the Lua being used is bundled by Minetest and not from my system.

**Comment by bell07** [comment]
I am Lua newbie and cannot replicate the issue. I get the mentioned message displayed in output. And I cannot understand the issue because "arg" is a table by lua syntax definiton, corresponding to "..." in function interface.
But I see the redirection does no sense during the init stage, so I fixed it. Maybe that is the issue reason? Please check if the fix solve your issue too. If not, any idea what is wrong?
I can fix it by "if type(arg) = string, print string, else loop table" but I like to understand the issue.

**Comment by Wuzzy2** [comment]
Sorry, I don't know how to help either. :-(

**Comment by bell07** [comment]
Can you please give a fresh error message if the issue still persists on our installation? Since my last changes on the mod the issue should not appear anymore in init-stage

**Comment by Wuzzy2** [comment]
Now the world does not instantly fail, but I still get a crash after placing a QA block:
```
2017-01-02 20:47:31: ACTION[Server]: singleplayer places node qa_block:block at (60,53,-344)
2017-01-02 20:47:31: WARNING[Server]: Undeclared global variable "arg" accessed at .../src/minetest/git/minetest/bin/../mods/qa_block/init.lua:51
2017-01-02 20:47:31: ERROR[Main]: ServerError: Lua: Runtime error from mod 'qa_block' in callback item_OnPlace(): .../src/minetest/git/minetest/bin/../mods/qa_block/init.lua:51: bad argument #1 to 'ipairs' (table expected, got nil)
2017-01-02 20:47:31: ERROR[Main]: stack traceback:
2017-01-02 20:47:31: ERROR[Main]: 	[C]: in function 'ipairs'
2017-01-02 20:47:31: ERROR[Main]: 	.../src/minetest/git/minetest/bin/../mods/qa_block/init.lua:51: in function 'print'
2017-01-02 20:47:31: ERROR[Main]: 	.../src/minetest/git/minetest/bin/../mods/qa_block/init.lua:82: in function 'do_source'
2017-01-02 20:47:31: ERROR[Main]: 	.../src/minetest/git/minetest/bin/../mods/qa_block/init.lua:106: in function 'do_module'
2017-01-02 20:47:31: ERROR[Main]: 	.../src/minetest/git/minetest/bin/../mods/qa_block/init.lua:180: in function 'after_place_node'
2017-01-02 20:47:31: ERROR[Main]: 	...y/src/minetest/git/minetest/bin/../builtin/game/item.lua:296: in function <...y/src/minetest/git/minetest/bin/../builtin/game/item.lua:199>
2017-01-02 20:47:31: ACTION[Server]: singleplayer leaves game. List of players: 
```

Minetest: a1346c916e1d0f0cde2ccecc680857896c717a3d
qa_block: b89d20bf0b498a8289d1adc0781cb36ff7a8148a

**Comment by bell07** [comment]
`WARNING[Server]: Undeclared global variable "arg" accessed at .../src/minetest/git/minetest/bin/../mods/qa_block/init.lua:51`

Can you please check your copy of the mod? I can reproduce the issue if I modify the line 47. The line should be
`print = function(...)`
in brackets is 3x the dot (.)
If I change the "..." to "test" (or any other string) I get the message with undeclared "arg" too.

**Comment by bell07** [comment]
Can you please test if you get the issue with a fresh "git clone"? Currently I have only the idea your copy is broken :(

**Comment by Wuzzy2** [comment]
Sorry, nothing changes with `git clone`. :-(

**Comment by bell07** [comment]
Next far-fetched idea, maybe any other mod does a redefinition of print function too. Did you tried with minetest_game or empty game? Otherwise I propose to set the line 5 (print_to_chat) to false and wait till the reason is found. Currently I am back to the stable 0.4.15 and do not have the development version.

**Comment by Wuzzy2** [comment]
Yeah, I tried with Empty + `qa_block` + `smartfs` + `origin` (start block to be able to build).
Same bug. Commit b89d20bf0b498a8289d1adc0781cb36ff7a8148a.

**Comment by bell07** [comment]
Hi, any change with issue after 5544d71?

**Comment by Wuzzy2** [comment]
No. It finally stopped crashing! Hooray!
